[settings]
  verbose = false
  debug = false
  site_dir = "site"
  build_dir = "build"

  page_file_extensions = ["htm", "html", "md"]
  keep_extensions = ["htm", "html"]
  ignore_directories = [".stfolder"]

  markdown_extensions = ["md"]

  default_template_file = "templates/main.html"
  default_content_selector = "content"
  default_content_action = "replace_element"

  generator_mode = true
  complete_page_selector = "html"

[templates.legacy_posts]
  file = "templates/legacy_posts.html"
  content_selector = "content"
  content_action = "replace_element"
  path_regex = "(200.|201.|2020|2024)/.*$"

[templates.posts]
  file = "templates/posts.html"
  content_selector = "content"
  content_action = "replace_element"
  path_regex = "(20[^012].|202[^01234])/.*$"

[widgets.header]
  widget = "include"
  file = "templates/head_shared.html"
  selector = "head"
  action = "prepend_child"

[widgets.footer]
  widget = "include"
  file = "templates/footer_shared.html"
  selector = "body"
  action = "append_child"

[widgets.header-navbar]
  widget = "include"
  file = "templates/header_navbar.html"
  selector = "header#navbar"
  action = "replace_element"

[widgets.page-title]
  widget = "title"
  selector = "h1"
  default = "Edinburgh Hacklab"
  append = " | Edinburgh Hacklab"
  force = true
  keep = true

[index]
  sort_by = "date"
  sort_descending = true

[index.views.posts]
  path_regex = "[0-9]{4}/.*$"
  index_selector = "#posts-index"
  index_item_template = """
    <article class="index-article">
        <span class="caption">{{date}}</span>
        <h2><a href="{{url}}">{{title}}</a></h2>
    </article>
  """

[index.fields]

[index.fields.title]
  selector = ["h1#post-title", "h1"]

[index.fields.date]
  selector = ["time#post-date", "time", "date"]
  extract_attribute = "datetime"
  fallback_to_content = true

[widgets.fix-relative-links]
  widget = "fix-relative-links"
